name: 'Bike Club Starter'
type: Site
description: 'Base recipe for a Bike Club website: admin tools and user roles.'
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/basic_block_type
  - core/recipes/user_picture
  # Include content_type_base here so page_access taxonomy terms are imported with TIDs = 1,2,3 (specified in tac_lite settings).
  - bikeclub_content_type_base
install:
  - admin_toolbar
  - admin_toolbar_tools
  - config
  - contextual
  - field_ui
  - help
  - history
  - menu_ui
  - menu_link_content
  - olivero
  - user
  - views_ui
  # Contrib - add 'admin_toolbar_tools' when compatible with project_browser
  - automatic_updates
  - automatic_updates_extensions
  - coffee
  - config_ignore
  - gin
  - login_emailusername
  - menu_admin_per_menu
  - menu_block
  - project_browser
  - redirect
  - token  
config:
  strict: false
  import:
    gin: '*'
    # Exclude Search forms.
    olivero: 
      - block.block.olivero_account_menu
      - block.block.olivero_breadcrumbs
      - block.block.olivero_content
      - block.block.olivero_help
      - block.block.olivero_main_menu
      - block.block.olivero_messages
      - block.block.olivero_page_title
      - block.block.olivero_powered
      - block.block.olivero_primary_admin_actions
      - block.block.olivero_primary_local_tasks
      - block.block.olivero_secondary_local_tasks
      - block.block.olivero_site_branding
      - block.block.olivero_syndicate
    redirect:
      - system.action.redirect_delete_action
      - views.view.redirect
    user:
      - views.view.who_s_online
  actions:
    automatic_updates.settings:
      simpleConfigUpdate:
        allow_core_minor_updates: true
    gin.settings:
      simpleConfigUpdate:
        classic_toolbar: horizontal
    project_browser.admin_settings:
      simpleConfigUpdate:
        allowed_projects:
          recipes:
            - bikeclub_announcements
            - bikeclub_civicrm
            - bikeclub_default_content
            - bikeclub_dev
            - bikeclub_editorial_workflow
            - bikeclub_events
            - bikeclub_faqs
            - bikeclub_member_directory
            - bikeclub_page
            - bikeclub_paragraph_types
            - bikeclub_webform_nodes
        enabled_sources:
          - drupalorg_jsonapi
          - recipes
        allow_ui_install: true
        max_selections: 1
    system.site:
      simpleConfigUpdate:
        page:
          front: '/node'
    system.theme:
      simpleConfigUpdate:
        admin: gin
        default: olivero
    user.settings:
      simpleConfigUpdate:
        register: admin_only
