name: 'Drupal for Bike Clubs'
type: Site
description: 'Base recipe for a Bike Club website (admin tools and user roles).'
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/basic_block_type
  - core/recipes/user_picture
  - bikeclub_page
install:
  - announcements_feed
  - config
  - contextual
  - field_ui
  - help
  - history
  - layout_builder
  - layout_discovery
  - menu_ui
  - menu_link_content
  - navigation
  - node
  - olivero  
  - views_ui
  # Contrib - add 'admin_toolbar_tools' when compatible with project_browser
  - admin_toolbar
  - automatic_updates
  - automatic_updates_extensions
  - bikeclub_olivero
  - coffee
  - config_ignore
  - dashboard
  - gin
  - gin_toolbar
  - login_emailusername
  - menu_admin_per_menu
  - menu_block
  - pathauto
  - project_browser
  - redirect
  - token  
config:
  strict: false
  import:
    bikeclub_olivero: '*'  
    node:
      # Import config which is imported by the Standard profile,
      # exclude view_mode.rss, include optional views.
      - core.entity_view_mode.node.full
      - core.entity_view_mode.node.teaser
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
      - views.view.content
      - views.view.frontpage
    gin: '*'
    navigation: '*'
    claro: '*'
    user:
      # This view mode is only needed because Olivero expects it to exist
      # in certain situations.
      - core.entity_view_mode.user.compact
      - views.view.user_admin_people
  actions:
    automatic_updates.settings:
      simpleConfigUpdate:
        allow_core_minor_updates: true
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    project_browser.admin_settings:
      simpleConfigUpdate:
        allowed_projects:
          recipes:
            - bikeclub_announcements
            - bikeclub_faqs
            - bikeclub_webform_nodes
            - bikeclub_default_content
            - bikeclub_editorial_workflow
            - bikeclub_member_directory
            - bikeclub_paragraph_types
        enabled_sources:
          - drupalorg_jsonapi
          - recipes
        allow_ui_install: true
        max_selections: 1
    system.site:
      simpleConfigUpdate:
        page.front: '/welcome'
    system.theme:
      simpleConfigUpdate:
        admin: claro
        default: olivero
    user.settings:
      simpleConfigUpdate:
        register: admin_only
