name: 'Bike Club Starter'
type: Site
description: 'Base recipe for a Bike Club website: admin tools and user roles.'
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/basic_block_type
  - core/recipes/user_picture
  # Important to include this here so page_access taxonomy terms are imported with TIDs = 1,2,3 (specified in tac_lite settings).
  - bikeclub_content_type_base
install:
  - config
  - contextual
  - field_ui
  - help
  - history
  - layout_builder
  - layout_discovery
  - menu_ui
  - menu_link_content
  - navigation
  - olivero
  - views_ui
  # Contrib - add 'admin_toolbar_tools' when compatible with project_browser
  - automatic_updates
  - automatic_updates_extensions
  - coffee
  - config_ignore
  - dashboard
  - gin
  - gin_toolbar
  - login_emailusername
  - menu_admin_per_menu
  - menu_block
  - project_browser
  - redirect
  - token  
config:
  strict: false
  import:
    bikeclub_olivero: '*'  
    claro: '*'
    gin: '*'
    navigation: '*'
  actions:
    automatic_updates.settings:
      simpleConfigUpdate:
        allow_core_minor_updates: true
    project_browser.admin_settings:
      simpleConfigUpdate:
        allowed_projects:
          recipes:
            - bikeclub_announcements
            - bikeclub_civicrm
            - bikeclub_default_content
            - bikeclub_dev
            - bikeclub_editorial_workflow
            - bikeclub_events
            - bikeclub_faqs
            - bikeclub_member_directory
            - bikeclub_page
            - bikeclub_paragraph_types
            - bikeclub_webform_nodes
        enabled_sources:
          - drupalorg_jsonapi
          - recipes
        allow_ui_install: true
        max_selections: 1
    system.site:
      simpleConfigUpdate:
        page.front: '/node'
    system.theme:
      simpleConfigUpdate:
        admin: gin
        default: olivero
    tac_lite:
      simpleConfigUpdate:
        tac_lite_categories:
          page_access: page_access
        tac_lite_schemes: 1
        menu_rebuild_needed: true
        tac_lite_config_scheme_1:
          name: 'View access'
          perms:
            grant_view: grant_view
          unpublished: 0
          term_visibility: 0
        # 1=Admin, 2=Members, 3=Ride leaders.
        # IDs = 1,2,3 depend on these terms being imported first by bikeclub_content_base.
        tac_lite_grants_scheme_1:
          anonymous:
            page_access: {  }
          authenticated:
            page_access: {  }
          administrator:
            page_access:
              1: '1'
              2: '2'
              3: '3'
          member:
            page_access:
              2: '2'
          ride_leader:
            page_access:
              3: '3'
          rides_coordinator:
            page_access:
              2: '2'
              3: '3'
          membership:
            page_access:
              2: '2'
              3: '3'
          site_admin:
            page_access:
              1: '1'
              2: '2'
              3: '3'
    user.settings:
      simpleConfigUpdate:
        register: admin_only
    views.view.who_s_online.yml:
      simpleConfigUpdate:
        display_options:
          access:
            type: role
            options:
              role:
                administrator: administrator

